version: '3'

networks:
  mailer:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_${APP_NAME}
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
    networks:
      - mailer

  mysql:
    image: mysql:5.7.33
    container_name: mysql_${APP_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mailer
      MYSQL_USER: havt
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 123456aa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - mailer

  php:
    image: havt/mailer_php
    container_name: php_${APP_NAME}
    volumes:
      - ./:/var/www/html/
    ports:
      - 9000:9000
    networks:
      - mailer
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 150MB
        reservations:
          cpus: '0.25'
          memory: 50MB
      restart_policy:
        condition: on-failure
